const Images = {
  ar1: require('./ar1.svg').default,
  logo: require('./logo.png'),
  arrow: require('./arrow.svg').default,
  vdeo: require('./vdeo.svg').default,
  video: require('./1 Introduction_to_React_and_Redux.mp4'),
  camera: require('./camera.svg').default,
  profilelogo: require('./profilelogo.png'),
  profile: require('./profile.svg').default,
  courses: require('./courses.svg').default,
  attend: require('./attendancec.svg').default,
  logout: require('./logout.svg').default,
  topic: require('./topic.svg').default,
  student: require('./students.svg').default,
  note: require('./notes.svg').default,
  chat: require('./chat.svg').default,
  yourcourses: require('./yourcourses.svg').default,
  check: require('./checkmark.svg').default,
  close: require('./close.svg').default,
  msg: require('./msg.svg').default,
  ham: require('./hamburger.svg').default,
  downarrow: require('./arrowdown.svg').default,
  search: require('./search.svg').default,
  file: require('./file.svg').default,
  emoji: require('./emoji.svg').default,
  upload: require('./upload.svg').default,
  submit: require('./submit.svg').default,
  fail: require('./fail.svg').default,
  facebook: require('./facebook.svg').default,
  linkden: require('./linkedin.svg').default,
  twitter: require('./twitter.svg').default,
  react: require('./react.png'),
  hide: require('./hide.png'),
  see: require('./see.png'),
  back: require('./background.png'),
  prof : require ('./prof.svg').default,
  cart : require ('./cart.svg').default,
  sus1 : require ('./sus1.jpg'),
  sus2 : require ('./sus2.jpg'),
  
}
export default Images
